[package]
name = "halo2-utils"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
halo2_proofs = { git = "https://github.com/privacy-scaling-explorations/halo2.git", tag = "v2023_04_20", features = ["dev-graph"] } 
# halo2_proofs = { path = "../../opensource/external/pse-halo2/halo2_proofs", features = ["dev-graph"] } 
snark-verifier-sdk = { git = "https://github.com/privacy-scaling-explorations/snark-verifier.git", rev = "a440ff91" } 
snark-verifier = { git = "https://github.com/privacy-scaling-explorations/snark-verifier.git", rev = "a440ff91" } 
plotters = "0.3.4"
rand_chacha = "0.3"
tabled = "0.14.0"
ethers = "2.0.7"

[patch."https://github.com/privacy-scaling-explorations/halo2.git"]
halo2_proofs = { path = "../../external/pse-halo2/halo2_proofs", features = ["dev-graph"] } 